# Generated by Django 4.1.4 on 2023-01-30 08:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_amount_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCompany',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='Name of tracking company provider', max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(default=None, help_text='Tracking number for order', max_length=128, null=True)),
                ('recipient_name', models.CharField(default=None, help_text='Full name of order recipient', max_length=128, null=True)),
                ('order', models.ForeignKey(help_text='Order associated with shipment', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order')),
                ('tracking_company', models.ForeignKey(default=None, help_text='Tracking company associated with shipment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_company', to='shipments.trackingcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
