# Generated by Django 4.1.4 on 2023-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcompany',
            name='name',
            field=models.CharField(default=None, help_text='Name of tracking company provider', max_length=128, null=True, unique=True),
        ),
    ]
