# Generated by Django 4.1.4 on 2023-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='recipient_name',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, default=None, help_text='Tracking number for order', max_length=128, null=True),
        ),
    ]
