# Generated by Django 4.1.4 on 2023-01-30 00:41

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], help_text='Status of order', max_length=128)),
                ('product', models.ForeignKey(help_text='Product associated with order', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
