# Generated by Django 4.1.4 on 2023-01-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_amount_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
